version: '1.1.{build}'
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - dotnet restore
  - dotnet build -c %CONFIGURATION%
test:
  assemblies:
    only:
      - DotNetEnv.Tests.dll
      - DotNetEnvTraverse.Tests.dll
deploy:
  - provider: NuGet
    api_key:
      secure: swhQ0dEHkSkmzA8qUk8BdLxWoJMjRWsWZz3W4H7VkxfPAzMYPnZuQMnYLRdgNcRe
cache:
  - '%LocalAppData%\NuGet\v3-cache'
